# ~/.config/starship.toml

format = """
[](#59205e)\
$env_var\
$username\
[](fg:#59205e bg:#7f187f)\
$directory\
[](fg:#7f187f bg:#01768b)\
$git_branch\
$git_status\
${custom.git_scope}\
[](fg:#01768b bg:#86BBD8)\
$c\
$golang\
$java\
$kotlin\
$nodejs\
$php\
$python\
$rust\
[](fg:#86BBD8 bg:#414141)\
$docker_context\
[](fg:#414141 bg:#82d170)\
$time\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[env_var.STARSHIP_DISTRO]
format = '[$env_value ](bg:#59205e fg:#ffffff)'
variable = "STARSHIP_DISTRO"
disabled = false

[username]
show_always = true
style_user = "bg:#59205e"
style_root = "bg:#59205e"
format = '[$user ]($style)'

[directory]
style = "bg:#7f187f fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = "C "
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#414141"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#01768b fg:#eeeeee"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#01768b"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "go"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "java"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = "kt"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "node"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "php"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "py"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "rust"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#82d170 fg:#414141"
format = '[  $time ]($style)'

[character]
success_symbol = "[](fg:#82d170)"
error_symbol = "[](fg:#82d170 bg:#c91f24)[](fg:#c91f24)"

[custom.git_scope]
# Inspired by:
#   - https://github.com/starship/starship/discussions/1252#discussioncomment-2461567
#   - https://github.com/starship/starship/issues/3644#issuecomment-1081886539
command = '''
printf "%s" \
  "$(if [ -n "$GIT_AUTHOR_EMAIL" ]; then echo "$GIT_AUTHOR_EMAIL"; else git config user.email; fi)"
'''
description = 'The currently configured Git user.email'
format = '[as $output ]($style)'
style = "bg:#01768b fg:#eeeeee"
# shell = ["dash"]
when = 'git rev-parse --is-inside-work-tree'
