# ~/.config/starship.toml

format = """
[](#59205e)\
$username\
[](fg:#59205e bg:#7f187f)\
$directory\
[](fg:#7f187f bg:#01768b)\
$git_branch\
$git_status\
[](fg:#01768b bg:#86BBD8)\
$c\
$golang\
$java\
$kotlin\
$nodejs\
$php\
$python\
$rust\
[](fg:#86BBD8 bg:#82d170)\
$time\
$character\
"""

[username]
show_always = true
style_user = "bg:#59205e"
style_root = "bg:#59205e"
format = '[ ]($style)'

[directory]
style = "bg:#7f187f fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "

[c]
symbol = "C "
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#01768b fg:#eeeeee"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#01768b"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "go"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "java"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = "kt"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "node"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "php"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "py"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "rust"
style = "bg:#86BBD8 fg:#414141"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#82d170 fg:#414141"
format = '[  $time ]($style)'

[character]
success_symbol = "[](fg:#82d170)"
error_symbol = "[](fg:#82d170 bg:#c91f24)[](fg:#c91f24)"

